export function generateJSONReport(scanData: any): string {
  return JSON.stringify(
    {
      reportName: 'Digital Footprint Exposure Report',
      target: scanData.target,
      scanType: scanData.type,
      riskScore: scanData.riskScore,
      scannedAt: new Date(scanData.createdAt).toISOString(),
      findingsCount: scanData.findings.length,
      findings: scanData.findings.map((f: any) => ({
        category: f.category,
        severity: f.severity,
        title: f.title,
        description: f.description,
        remediation: f.remediation
      }))
    },
    null,
    2
  );
}

export function generateCSVReport(scanData: any): string {
  const headers = ['Category', 'Severity', 'Title', 'Description', 'Remediation'];
  const rows = scanData.findings.map((f: any) => [
    escapeCSV(f.category),
    escapeCSV(f.severity),
    escapeCSV(f.title),
    escapeCSV(f.description),
    escapeCSV(f.remediation)
  ]);

  return [
    `Target,${escapeCSV(scanData.target)},Scan Type,${scanData.type},Risk Score,${scanData.riskScore}`,
    headers.join(','),
    ...rows.map((row: string[]) => row.join(','))
  ].join('\n');
}

export function generateHTMLReport(scanData: any): string {
  const findingsRows = scanData.findings.map((f: any) => `
    <tr>
      <td style="padding: 12px; border-bottom: 1px solid #ddd; font-weight: bold;">${f.category}</td>
      <td style="padding: 12px; border-bottom: 1px solid #ddd;">
        <span class="badge ${f.severity.toLowerCase()}">${f.severity}</span>
      </td>
      <td style="padding: 12px; border-bottom: 1px solid #ddd;">${f.title}</td>
      <td style="padding: 12px; border-bottom: 1px solid #ddd; font-size: 14px; color: #555;">${f.description}</td>
      <td style="padding: 12px; border-bottom: 1px solid #ddd; font-size: 14px; color: #0066cc;">${f.remediation}</td>
    </tr>
  `).join('');

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Digital Footprint Analyzer Report - ${scanData.target}</title>
      <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; color: #333; line-height: 1.6; }
        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 3px solid #0056b3; padding-bottom: 20px; margin-bottom: 30px; }
        .title { font-size: 28px; font-weight: bold; color: #0056b3; margin: 0; }
        .meta-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; background: #f9f9f9; }
        .meta-table td, .meta-table th { padding: 12px; border: 1px solid #ddd; text-align: left; }
        .meta-table th { background: #f1f1f1; font-weight: bold; width: 25%; }
        .score-box { background: #ffebeb; border: 2px solid #ff4d4d; border-radius: 8px; padding: 20px; text-align: center; margin-bottom: 30px; }
        .score-val { font-size: 48px; font-weight: bold; color: #ff4d4d; margin: 0; }
        .score-label { font-size: 14px; color: #777; text-transform: uppercase; letter-spacing: 1px; }
        table.findings { width: 100%; border-collapse: collapse; margin-top: 20px; }
        table.findings th { background: #0056b3; color: white; padding: 12px; text-align: left; }
        table.findings td { padding: 12px; border: 1px solid #ddd; }
        .badge { padding: 4px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; text-transform: uppercase; color: white; }
        .badge.critical { background-color: #d9534f; }
        .badge.high { background-color: #f0ad4e; }
        .badge.medium { background-color: #5bc0de; }
        .badge.low { background-color: #5cb85c; }
        .badge.info { background-color: #777; }
        .footer { margin-top: 50px; font-size: 12px; color: #888; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
        @media print {
          body { margin: 20px; font-size: 12px; }
          .header { margin-bottom: 20px; }
          button { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <h1 class="title">Digital Footprint & Exposure Report</h1>
          <p style="margin: 5px 0 0 0; color: #666;">Generated by Aegis Footprint Analyzer</p>
        </div>
        <button onclick="window.print()" style="padding: 10px 20px; background: #0056b3; color: white; border: none; border-radius: 4px; cursor: pointer; font-weight: bold;">Print / Save as PDF</button>
      </div>

      <div style="display: flex; gap: 30px;">
        <div style="flex: 2;">
          <table class="meta-table">
            <tr>
              <th>Scan Target</th>
              <td>${scanData.target}</td>
            </tr>
            <tr>
              <th>Scan Type</th>
              <td>${scanData.type}</td>
            </tr>
            <tr>
              <th>Scanned At</th>
              <td>${new Date(scanData.createdAt).toLocaleString()}</td>
            </tr>
            <tr>
              <th>Total Findings</th>
              <td>${scanData.findings.length} issues identified</td>
            </tr>
          </table>
        </div>
        
        <div style="flex: 1;">
          <div class="score-box" style="background: ${getScoreBackground(scanData.riskScore)}; border-color: ${getScoreColor(scanData.riskScore)};">
            <h2 class="score-label" style="color: ${getScoreColor(scanData.riskScore)};">Privacy Risk Score</h2>
            <p class="score-val" style="color: ${getScoreColor(scanData.riskScore)};">${scanData.riskScore}/100</p>
            <p style="margin: 5px 0 0 0; font-weight: bold; color: ${getScoreColor(scanData.riskScore)};">${getScoreCategory(scanData.riskScore)}</p>
          </div>
        </div>
      </div>

      <h2>Exposed Findings Details</h2>
      <table class="findings">
        <thead>
          <tr>
            <th style="width: 15%;">Category</th>
            <th style="width: 10%;">Severity</th>
            <th style="width: 20%;">Finding</th>
            <th style="width: 30%;">Description</th>
            <th style="width: 25%;">Remediation Action</th>
          </tr>
        </thead>
        <tbody>
          ${findingsRows}
        </tbody>
      </table>

      <div class="footer">
        <p>CONFIDENTIAL REPORT - Generated for privacy auditing purposes only. All data obtained via public sources and user consent.</p>
        <p>Aegis Privacy Cleaner 2026. All rights reserved.</p>
      </div>
    </body>
    </html>
  `;
}

function escapeCSV(val: any): string {
  if (val === undefined || val === null) return '';
  const str = String(val);
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function getScoreColor(score: number): string {
  if (score >= 70) return '#d9534f'; // red
  if (score >= 35) return '#f0ad4e'; // yellow
  return '#5cb85c'; // green
}

function getScoreBackground(score: number): string {
  if (score >= 70) return '#fdf2f2'; // light red
  if (score >= 35) return '#fefaf3'; // light yellow
  return '#f2faf2'; // light green
}

function getScoreCategory(score: number): string {
  if (score >= 70) return 'HIGH EXPOSURE';
  if (score >= 35) return 'MODERATE EXPOSURE';
  return 'SECURE / LOW EXPOSURE';
}
